name: Deploy Helm Chart

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0

      - name: Add Helm repository
        run: helm repo add myapp https://siamese-lang.github.io/rapa-helm-repo

      - name: Update Helm repositories
        run: helm repo update

      - name: Create Kubeconfig directory
        run: mkdir -p $HOME/.kube

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config

      - name: Install or Upgrade Helm chart
        run: |
          helm upgrade --install java-app myapp/myapp  # Helm 차트 설치 또는 업그레이드
