name: Deploy Helm Chart

on:
  workflow_run:
    workflows: ["pages-build-deployment"]  # 첫 번째 워크플로우 이름
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'  # 사용하고 있는 AWS 리전으로 변경

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0  # 사용할 Helm 버전

      - name: Add Helm repository
        run: helm repo add siamese https://siamese-lang.github.io/helm-repo-test  # Helm 레포지토리 추가

      - name: Update Helm repositories
        run: helm repo update  # Helm 레포지토리 업데이트

      - name: Create Kubeconfig directory
        run: mkdir -p $HOME/.kube  # Kubeconfig 디렉토리 생성

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config  # Kubeconfig 파일 생성

      - name: Install or Upgrade Helm chart
        run: |
          helm upgrade --install myapp https://siamese-lang.github.io/helm-repo-test/myapp  # Helm 차트 설치 또는 업그레이드
